my_tuple = (1,2,3,4,'Mohot',5.5)
# print(type(my_tuple))
# print(my_tuple[-5:-2])
my_list = list(my_tuple)
print(my_list)
my_list.append(100)
print(type(my_list))
my_tuple = tuple(my_list)
print(type(my_tuple))
print(my_tuple)
